### ISSUE TITLE
Refreshes the wrong window

### ISSUE THREAD

**Issue by thany** [StoyanDimitrov/css-reload#11]
I just noticed while I have two windows of Firefox open and both visible. I press Ctrl+F9 in one window, and the active tab in the other window refreshes its CSS. That probably shouldn't happen.

It appears the workaround is to open a tab in the correct window, which will sort of "activate" it (this is probably the same behaviour as when Firefox chooses in which window to open a link clicked from an different application). Doing this will cause the plugin to choose the correct window again.

I'm on Firefox Dev 62.0b5 on Windows 10.

Just a thought: could this have caused (at least in part) issue #8?

**Comment by thany** [comment]
If closed means fixed, when do you think you'll make a release? Thanks :)

**Comment by StoyanDimitrov** [comment]
There were several minor releases since this fix landed.

**Comment by thany** [comment]
Well, in that case, it's not fixed I'm afraid... My addons are up-to-date and this bug is still happening.

**Comment by StoyanDimitrov** [comment]
Hm, strangely I can not reproduce in release, beta, dev ed nor nightly; with clean and main profile; add-on latest from AMO. Can you give more detailed steps to reproduce? Does it happen after browser start or after some use?

**Comment by thany** [comment]
On my setup it only refreshes the last used tab of the window which had some kind of activity.

Here's how to reproduce (I think):
Have two Firefox windows, 1 and 2, each with a bunch of tabs open. Now go to the tab you want to refresh, and refresh it. It'll work. Now go to window number 2, do some stuff (it really doesn't matter what - uhh, F5 it or something). Go back to another *application*. Now click on the title bar of Firefox window number 1. Try the Ctrl+F9.

Result:
It will refresh window number 2. Wrong window, and consequently, wrong tab.

**Comment by StoyanDimitrov** [comment]
I never successfully reproduced the issue after initial report.

Still, I discovered and published fix for a possible internal state corruption.

If 0.3.5 doesn't fix your issue as last resort I'd recommend reinstall (as in uninstall and install again) the add-on.
