### ISSUE TITLE
Plugin not working in "responsive design mode"

### ISSUE THREAD

**Issue by glegault** [StoyanDimitrov/css-reload#5]
Using Firefox (using Developer Edition 57.0b3) developer tools, when I'm in "responsive design mode", the plugin stops working. If I exit the responsive design mode, the plugin starts working again.

**Comment by StoyanDimitrov** [comment]
Probably one of those pages that web ext are disabled. Still have to confirm.

**Comment by marktastic** [comment]
I'm seeing the same issue.

Temporary workaround for me is docking the dev tools to the right and expanding it.

**Comment by StoyanDimitrov** [comment]
It is not that the extension is disabled. As it seems the document is moved to different context. I'm in touch with devtools devs and will investigate further.

Edit: https://bugzil.la/1394841

**Comment by StoyanDimitrov** [comment]
[Bug 1394841](https://bugzil.la/1394841) has been fixed! It is targeted at Fx58.

**Comment by glegault** [comment]
The issue is still present in Firefox Developer Edition version 58.0b1 (64-bit).

**Comment by StoyanDimitrov** [comment]
The bug was fixed two days prior [the release](https://calendar.google.com/calendar/embed?src=bW96aWxsYS5jb21fZGJxODRhbnI5aTh0Y25taGFiYXRzdHY1Y29AZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ) of Firefox Developer Edition version 58.0b1, no matter how recently you got prompted for update.

**Comment by glegault** [comment]
And it's working now in 58.0b4! Thank you for fixing this!
